require('dotenv').config();
const mongoose = require('mongoose');
const GroceryItem = require('../src/models/groceryItem');
const Settings = require('../src/models/settings');

// MongoDB connection string
const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error('ERROR: MONGODB_URI environment variable not set');
  process.exit(1);
}

const groceryItems = [
  // ========================================
  // 🛒 GROCERY (20 Items)
  // ========================================
  {
    name: "Green Dragon Rice",
    brand: "Green Dragon",
    category: "Grocery",
    subcategory: "Rice",
    description: "Premium Thai jasmine rice",
    pack_size: "10kg",
    price: 18.99,
    currency: "GBP",
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Peacock Rice",
    brand: "Peacock",
    category: "Grocery",
    subcategory: "Rice",
    description: "Long grain basmati rice",
    pack_size: "10kg",
    price: 16.99,
    currency: "GBP",
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Sunflower Oil",
    brand: "Crisp 'n Dry",
    category: "Grocery",
    subcategory: "Cooking",
    description: "Pure sunflower cooking oil",
    pack_size: "5L",
    price: 9.49,
    currency: "GBP",
    stock: 60,
    image_url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Sardines in Oil",
    brand: "John West",
    category: "Grocery",
    subcategory: "Tinned",
    description: "Sardines in sunflower oil",
    pack_size: "120g x 6",
    price: 7.99,
    currency: "GBP",
    stock: 80,
    image_url: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Mackerel in Tomato Sauce",
    brand: "Princes",
    category: "Grocery",
    subcategory: "Tinned",
    description: "Mackerel fillets in rich tomato sauce",
    pack_size: "125g x 6",
    price: 8.49,
    currency: "GBP",
    stock: 70,
    image_url: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Evaporated Milk",
    brand: "Carnation",
    category: "Grocery",
    subcategory: "Dairy",
    description: "Creamy evaporated milk",
    pack_size: "410g x 6",
    price: 8.99,
    currency: "GBP",
    stock: 85,
    image_url: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Cornflakes",
    brand: "Kellogg's",
    category: "Grocery",
    subcategory: "Breakfast",
    description: "Classic golden corn flakes",
    pack_size: "750g",
    price: 3.99,
    currency: "GBP",
    stock: 65,
    image_url: "https://images.unsplash.com/photo-1517456793572-1d8efd6dc135?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Chopped Tomatoes",
    brand: "Napolina",
    category: "Grocery",
    subcategory: "Tinned",
    description: "Italian chopped tomatoes",
    pack_size: "400g x 6",
    price: 5.99,
    currency: "GBP",
    stock: 90,
    image_url: "https://images.unsplash.com/photo-1546548970-71785318a17b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Heroes Chocolate Box",
    brand: "Cadbury",
    category: "Grocery",
    subcategory: "Snacks",
    description: "Assorted chocolate selection",
    pack_size: "600g",
    price: 7.99,
    currency: "GBP",
    stock: 40,
    image_url: "https://images.unsplash.com/photo-1548907040-4bea42c2d7b5?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Nutella",
    brand: "Ferrero",
    category: "Grocery",
    subcategory: "Spreads",
    description: "Hazelnut chocolate spread",
    pack_size: "750g",
    price: 5.49,
    currency: "GBP",
    stock: 55,
    image_url: "https://images.unsplash.com/photo-1604514628550-37477afdf4e3?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Digestive Biscuits",
    brand: "McVitie's",
    category: "Grocery",
    subcategory: "Biscuits",
    description: "Original wheat digestives",
    pack_size: "400g x 2",
    price: 3.49,
    currency: "GBP",
    stock: 100,
    image_url: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Yellow Label Tea",
    brand: "Lipton",
    category: "Grocery",
    subcategory: "Drinks",
    description: "Classic black tea bags",
    pack_size: "100 bags",
    price: 3.99,
    currency: "GBP",
    stock: 75,
    image_url: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Original Tea Bags",
    brand: "PG Tips",
    category: "Grocery",
    subcategory: "Drinks",
    description: "British black tea",
    pack_size: "240 bags",
    price: 5.99,
    currency: "GBP",
    stock: 80,
    image_url: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Spaghetti",
    brand: "Napolina",
    category: "Grocery",
    subcategory: "Pasta",
    description: "Italian spaghetti pasta",
    pack_size: "500g x 4",
    price: 4.49,
    currency: "GBP",
    stock: 95,
    image_url: "https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Tomato Ketchup",
    brand: "Heinz",
    category: "Grocery",
    subcategory: "Sauces",
    description: "Classic tomato ketchup",
    pack_size: "700ml",
    price: 3.49,
    currency: "GBP",
    stock: 90,
    image_url: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Tomato Puree",
    brand: "Napolina",
    category: "Grocery",
    subcategory: "Cooking",
    description: "Concentrated tomato puree",
    pack_size: "200g x 3",
    price: 2.99,
    currency: "GBP",
    stock: 85,
    image_url: "https://images.unsplash.com/photo-1546548970-71785318a17b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Granulated Sugar",
    brand: "Tate & Lyle",
    category: "Grocery",
    subcategory: "Baking",
    description: "White granulated sugar",
    pack_size: "2kg",
    price: 2.49,
    currency: "GBP",
    stock: 100,
    image_url: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Baked Beans",
    brand: "Heinz",
    category: "Grocery",
    subcategory: "Tinned",
    description: "Beans in tomato sauce",
    pack_size: "415g x 4",
    price: 4.49,
    currency: "GBP",
    stock: 110,
    image_url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Shortbread Fingers",
    brand: "Walker's",
    category: "Grocery",
    subcategory: "Biscuits",
    description: "Pure butter shortbread",
    pack_size: "250g x 2",
    price: 4.99,
    currency: "GBP",
    stock: 65,
    image_url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Weetabix",
    brand: "Weetabix",
    category: "Grocery",
    subcategory: "Breakfast",
    description: "Whole grain wheat cereal",
    pack_size: "48 biscuits",
    price: 5.99,
    currency: "GBP",
    stock: 70,
    image_url: "https://images.unsplash.com/photo-1521483451569-e33803c0330c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },

  // ========================================
  // ⚡ ELECTRONICS (20 Items)
  // ========================================
  {
    name: "iPhone 12",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Phones",
    description: "64GB, Unlocked",
    pack_size: "1 unit",
    price: 449.00,
    currency: "GBP",
    stock: 10,
    image_url: "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "iPhone 13",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Phones",
    description: "128GB, Unlocked",
    pack_size: "1 unit",
    price: 579.00,
    currency: "GBP",
    stock: 8,
    image_url: "https://images.unsplash.com/photo-1632661674596-df8be59a6d95?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "iPhone 14",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Phones",
    description: "128GB, Unlocked",
    pack_size: "1 unit",
    price: 699.00,
    currency: "GBP",
    stock: 6,
    image_url: "https://images.unsplash.com/photo-1678652197831-2d180705cd2c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "iPhone 15",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Phones",
    description: "128GB, Unlocked",
    pack_size: "1 unit",
    price: 799.00,
    currency: "GBP",
    stock: 5,
    image_url: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "iPhone Charger",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Accessories",
    description: "20W USB-C Power Adapter",
    pack_size: "1 unit",
    price: 19.99,
    currency: "GBP",
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Lightning Cable",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Accessories",
    description: "USB-C to Lightning, 1m",
    pack_size: "1 unit",
    price: 15.99,
    currency: "GBP",
    stock: 60,
    image_url: "https://images.unsplash.com/photo-1558538337-aab544368de8?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "AirPods Pro",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Audio",
    description: "2nd Generation with MagSafe",
    pack_size: "1 unit",
    price: 229.00,
    currency: "GBP",
    stock: 15,
    image_url: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Apple Watch SE",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Wearables",
    description: "GPS, 44mm",
    pack_size: "1 unit",
    price: 259.00,
    currency: "GBP",
    stock: 12,
    image_url: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Samsung Galaxy A14",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Phones",
    description: "64GB, Dual SIM",
    pack_size: "1 unit",
    price: 149.00,
    currency: "GBP",
    stock: 20,
    image_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Samsung Galaxy A34",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Phones",
    description: "128GB, 5G",
    pack_size: "1 unit",
    price: 299.00,
    currency: "GBP",
    stock: 15,
    image_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Samsung Fast Charger",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Accessories",
    description: "25W Super Fast USB-C",
    pack_size: "1 unit",
    price: 17.99,
    currency: "GBP",
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1622674777904-46d0b9b22eed?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Power Bank 20000mAh",
    brand: "Anker",
    category: "Electronics",
    subcategory: "Accessories",
    description: "Fast charging portable charger",
    pack_size: "1 unit",
    price: 39.99,
    currency: "GBP",
    stock: 35,
    image_url: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Laptop 15.6 inch",
    brand: "HP",
    category: "Electronics",
    subcategory: "Computers",
    description: "Intel i5, 8GB RAM, 256GB SSD",
    pack_size: "1 unit",
    price: 449.00,
    currency: "GBP",
    stock: 8,
    image_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Android Tablet 10 inch",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Tablets",
    description: "Galaxy Tab A8, 32GB",
    pack_size: "1 unit",
    price: 199.00,
    currency: "GBP",
    stock: 12,
    image_url: "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "iPad 10th Gen",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Tablets",
    description: "64GB, Wi-Fi",
    pack_size: "1 unit",
    price: 349.00,
    currency: "GBP",
    stock: 10,
    image_url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "PlayStation 5 Console",
    brand: "Sony",
    category: "Electronics",
    subcategory: "Gaming",
    description: "Disc Edition",
    pack_size: "1 unit",
    price: 479.00,
    currency: "GBP",
    stock: 5,
    image_url: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "PS5 DualSense Controller",
    brand: "Sony",
    category: "Electronics",
    subcategory: "Gaming",
    description: "Wireless controller, White",
    pack_size: "1 unit",
    price: 59.99,
    currency: "GBP",
    stock: 20,
    image_url: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Xbox Wireless Controller",
    brand: "Microsoft",
    category: "Electronics",
    subcategory: "Gaming",
    description: "Carbon Black",
    pack_size: "1 unit",
    price: 54.99,
    currency: "GBP",
    stock: 18,
    image_url: "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Phone Cases Assorted",
    brand: "Generic",
    category: "Electronics",
    subcategory: "Accessories",
    description: "iPhone/Samsung compatible",
    pack_size: "3 pack",
    price: 12.99,
    currency: "GBP",
    stock: 100,
    image_url: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Screen Protectors",
    brand: "Generic",
    category: "Electronics",
    subcategory: "Accessories",
    description: "Tempered glass, universal",
    pack_size: "5 pack",
    price: 9.99,
    currency: "GBP",
    stock: 120,
    image_url: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },

  // ========================================
  // 🏠 HOUSEHOLD (20 Items)
  // ========================================
  {
    name: "Washing Powder",
    brand: "Ariel",
    category: "Household",
    subcategory: "Laundry",
    description: "Original laundry detergent",
    pack_size: "4.2kg",
    price: 14.99,
    currency: "GBP",
    stock: 40,
    image_url: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Thick Bleach",
    brand: "Domestos",
    category: "Household",
    subcategory: "Cleaning",
    description: "Extended germ-kill",
    pack_size: "750ml x 2",
    price: 4.99,
    currency: "GBP",
    stock: 60,
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Washing Up Liquid",
    brand: "Fairy",
    category: "Household",
    subcategory: "Cleaning",
    description: "Original dishwashing liquid",
    pack_size: "900ml",
    price: 3.49,
    currency: "GBP",
    stock: 70,
    image_url: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Fabric Softener",
    brand: "Comfort",
    category: "Household",
    subcategory: "Laundry",
    description: "Fresh sky scent",
    pack_size: "3L",
    price: 5.99,
    currency: "GBP",
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Baby Dry Nappies Size 4",
    brand: "Pampers",
    category: "Household",
    subcategory: "Baby",
    description: "9-14kg, mega pack",
    pack_size: "86 pack",
    price: 19.99,
    currency: "GBP",
    stock: 30,
    image_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Sensitive Baby Wipes",
    brand: "Pampers",
    category: "Household",
    subcategory: "Baby",
    description: "Fragrance free",
    pack_size: "12 x 52 wipes",
    price: 14.99,
    currency: "GBP",
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1584839404042-8bc21d240de8?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Baby Lotion",
    brand: "Johnson's",
    category: "Household",
    subcategory: "Baby",
    description: "Gentle moisturising lotion",
    pack_size: "500ml",
    price: 4.49,
    currency: "GBP",
    stock: 55,
    image_url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Total Toothpaste",
    brand: "Colgate",
    category: "Household",
    subcategory: "Personal Care",
    description: "Whitening toothpaste",
    pack_size: "125ml x 3",
    price: 6.99,
    currency: "GBP",
    stock: 80,
    image_url: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Toothbrush Medium",
    brand: "Oral-B",
    category: "Household",
    subcategory: "Personal Care",
    description: "Clean & fresh toothbrush",
    pack_size: "4 pack",
    price: 4.99,
    currency: "GBP",
    stock: 70,
    image_url: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Hand Sanitiser",
    brand: "Dettol",
    category: "Household",
    subcategory: "Personal Care",
    description: "Antibacterial gel",
    pack_size: "500ml x 2",
    price: 6.49,
    currency: "GBP",
    stock: 65,
    image_url: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Shower Gel Original",
    brand: "Dove",
    category: "Household",
    subcategory: "Personal Care",
    description: "Deeply nourishing",
    pack_size: "500ml x 2",
    price: 5.99,
    currency: "GBP",
    stock: 60,
    image_url: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Toilet Rolls",
    brand: "Andrex",
    category: "Household",
    subcategory: "Paper",
    description: "Classic white, soft",
    pack_size: "16 rolls",
    price: 9.99,
    currency: "GBP",
    stock: 50,
    image_url: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Kitchen Roll",
    brand: "Plenty",
    category: "Household",
    subcategory: "Paper",
    description: "Strong absorbent rolls",
    pack_size: "8 rolls",
    price: 7.49,
    currency: "GBP",
    stock: 55,
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Bin Bags Heavy Duty",
    brand: "Sainsbury's",
    category: "Household",
    subcategory: "Cleaning",
    description: "50L refuse bags",
    pack_size: "60 bags",
    price: 5.99,
    currency: "GBP",
    stock: 45,
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Scouring Sponges",
    brand: "Scotch-Brite",
    category: "Household",
    subcategory: "Cleaning",
    description: "Non-scratch sponges",
    pack_size: "10 pack",
    price: 3.99,
    currency: "GBP",
    stock: 80,
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Spin Mop Set",
    brand: "Vileda",
    category: "Household",
    subcategory: "Cleaning",
    description: "Easy wring mop & bucket",
    pack_size: "1 set",
    price: 24.99,
    currency: "GBP",
    stock: 25,
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Air Freshener",
    brand: "Febreze",
    category: "Household",
    subcategory: "Cleaning",
    description: "Spring awakening spray",
    pack_size: "300ml x 2",
    price: 5.49,
    currency: "GBP",
    stock: 60,
    image_url: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Antibacterial Hand Wash",
    brand: "Dettol",
    category: "Household",
    subcategory: "Personal Care",
    description: "Original liquid soap",
    pack_size: "500ml x 3",
    price: 7.49,
    currency: "GBP",
    stock: 55,
    image_url: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Laundry Capsules",
    brand: "Ariel",
    category: "Household",
    subcategory: "Laundry",
    description: "All-in-1 pods",
    pack_size: "51 pods",
    price: 12.99,
    currency: "GBP",
    stock: 40,
    image_url: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  },
  {
    name: "Surface Cleaner",
    brand: "Dettol",
    category: "Household",
    subcategory: "Cleaning",
    description: "Antibacterial spray",
    pack_size: "750ml x 2",
    price: 5.99,
    currency: "GBP",
    stock: 65,
    image_url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400",
    fulfilled_by: "ManiMe UK",
    shipping: "UK → Ghana",
    is_available: true
  }
];

async function seedGroceryData() {
  try {
    // Connect to MongoDB
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing grocery items
    await GroceryItem.deleteMany({});
    console.log('Cleared existing grocery items');

    // Insert new items
    await GroceryItem.insertMany(groceryItems);
    console.log(`Seeded ${groceryItems.length} grocery items`);

    // Set UK to Ghana shipping rate
    await Settings.findOneAndUpdate(
      { key: 'uk_ghana_shipping_rate' },
      {
        key: 'uk_ghana_shipping_rate',
        value: '15.00',
        description: 'Flat rate shipping cost from UK to Ghana for grocery orders (in GBP)'
      },
      { upsert: true, new: true }
    );
    console.log('Set UK to Ghana shipping rate: £15.00');

    console.log('\n✅ Grocery shop data seeded successfully!');
    console.log('\nCategories:');
    console.log(`- Grocery: ${groceryItems.filter(i => i.category === 'Grocery').length} items`);
    console.log(`- Electronics: ${groceryItems.filter(i => i.category === 'Electronics').length} items`);
    console.log(`- Household: ${groceryItems.filter(i => i.category === 'Household').length} items`);
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
}

seedGroceryData();
